name: daphne

packages:
  - packages/*

scripts:
  build_runner:
    exec: dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner for each project.

  lint:
    exec: dart analyze
    description: Run dart analyze for each project.
