name: daphne_io
description: The Native (Dart IO) components for Daphne.
version: 0.0.1
repository: https://github.com/apollosoftwarexyz/daphne

environment:
  sdk: ^3.0.0

dependencies:
  daphne_http: ^1.2.1
  daphne: ^1.0.0

  freezed_annotation: ^2.2.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  lints: ^2.0.0
  test: ^1.21.0
