name: daphne
description: An HTTP library for Dart and Flutter.
version: 0.0.1
repository: https://github.com/apollosoftwarexyz/daphne

environment:
  sdk: ^3.0.0

dependencies:
  freezed_annotation: ^2.2.0
  daphne_http: ^1.2.1
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  lints: ^2.0.0
  test: ^1.21.0
